### ISSUE TITLE
specify datatype for literal generator

### ISSUE THREAD

**Issue by robcast** [isl/x3ml#137]
When generating a literal using the 3M web frontend I can specfify the language of a langString (`language` argument) but not the datatype. It would be good to be able to specify that some string has a type of e.g. xsd:Date.

Is there such an argument for the generator that I didn't know about?

**Comment by ymark** [comment]
You can define the type of a literal value using the TypedLiteralGenerator. Check #111

**Comment by robcast** [comment]
This looks like what I need but how can I use it with the 3M web frontend?

I added a TypedLiteralGenerator to my generator.xml like in the example but it only has a `text` argument. How do I set the `type`? 

It currently generates ```"1222-02-20"^^rdfs:Literal .```

**Comment by ymark** [comment]
Apart from declaring TypedLiteralGenerator in your generator policy file, you have to use this generator when creating an instance for your resources. Practically: 
You'll have to define that the entity you will generate has the type of interest (e.g. xsd:date)
and then in the generators tab, you have to use TypedLiteralGenerator for this entity. Below, you'll find the corresponding part from the X3ML serialization.

```
<target_node>
	<entity>
		<type>xsd:date</type>
		<instance_generator name="TypedLiteralGen">
			<arg name="text">text()</arg>
		</instance_generator>
	</entity>
</target_node>
```

**Comment by ncarboni** [comment]
@ymark I think it will not work in 3M 

If you want to use datatype in 3M I would suggest to add a target schema which describe xsd datatype and then set the type on the mapping.
However, the XSD target schema has never made available. There is this unofficial one made by Gregg Kellogg:

https://github.com/ruby-rdf/rdf/blob/develop/etc/xsd.ttl

**Comment by robcast** [comment]
@ncarboni thanks for the link to the XSD schema and indeed, it is not easy to change the type of an entity in 3M.

I managed to change the type manually when I switch off the target analyzer and then the type generation works but 3M will complain every time the analyzer is switched on again.

Also it is problematic to change the type when the mapping is part of a CRM chain because the only type allowed by the analyzer is rdfs:Literal. Adding xsd:date as an additional class leads to an error in the generator.

For this use case it would be really helpful to have an optional `type` argument to the generator that overrides the type of the entity.

**Comment by ncarboni** [comment]
That is probably due because of the lack of connections between xsd type and rdfs:literal in the [linked turtle file](https://github.com/ruby-rdf/rdf/blob/develop/etc/xsd.ttl)

You will probably resolve if you declare xsd:anyType as subclass of literal in the ttl as

```turtle
xsd:anyType a rdfs:Datatype;
rdfs:subClassOf rdfs:Literal;
  rdfs:label "anyType";
```

**Comment by robcast** [comment]
I still think an optional type argument would be handy for use in 3M but the solution using TypedLiteralGenerator and a hacked XSD schema works, so I'll close the ticket.
