### ISSUE TITLE
Validate Generator policy files

### ISSUE THREAD

**Issue by ymark** [isl/x3ml#138]
Validate the XML serialization of generator policy files w.r.t. the default XSD.

**Comment by ymark** [comment]
Generator policy files are now validated w.r.t. a XSD schema file. The XSD and its documentation can be found at https://github.com/isl/x3ml/tree/master/resources/X3ML%20Schema.

The validation mechanism will be made available from 1.9.4

**Comment by ncarboni** [comment]
Hi, would you mind adding an example of a new generator policy ? (seemed appropriate to have it here, but i can open another issue if you prefer 👍)

**Comment by ymark** [comment]
Sure. You can find it attached. 
In addition, it has been added as a template at https://github.com/isl/x3ml/tree/master/resources
[generator-policy-template.xml.txt](https://github.com/isl/x3ml/files/6471389/generator-policy-template.xml.txt)

**Comment by ymark** [comment]
[generator-policy-template.xml.txt](https://github.com/isl/x3ml/files/6471390/generator-policy-template.xml.txt)

**Comment by ncarboni** [comment]
Thanks :-)
