### ISSUE TITLE
Generator URL-encodes reserved characters

### ISSUE THREAD

**Issue by fkraeutli** [isl/x3ml#139]
I have an attribute I want to use in an URI that contains an exclamation mark:
`<mets:mets OBJID="21.11101!0000-0007-DB2E-0"></mets:mets>`

I'm using the LocalTermURI Generator to create an URI.

I would like to get an URI of the form `<http://example.org/resource/21.11101!0000-0007-DB2E-0>`. However the exclamation mark gets encoded into: `<http://example.org/resource/21.11101%210000-0007-DB2E-0>`

Is there a way to prevent this?

I looked a bit into it and saw that UriComponentsBuilder.encode() also encodes reserved characters, whereas UriComponents.encode() does not. Would it be possible to switch encoding and would that bring about the desired effect?

https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/util/UriComponentsBuilder.html#encode--

https://github.com/isl/x3ml/blob/8224b1cb8307eca5900cd742cc94d907bd918a0d/src/main/java/gr/forth/UriValidator.java#L65

**Comment by ymark** [comment]
The encode option has been added on purpose (it encodes non-accepted characters as well).
In addition, it cannot be disabled. 

The only option you can follow is to get rid of it in your own x3ml engine fork.

**Comment by fkraeutli** [comment]
Closing this. We added some post-processing to the output.
